travis:
  secure:
    BINSTAR_TOKEN: I7nOVNo3C20eablMY6Vi/KsqEU7TufTAFfzQ7vtmtP7bfxGrYkIJOvyVMrVBQg/ACbeOF4E2IC2d2BHtT99GGXU6sLGGqGzLDiDM5ZPAXldNHY8vx+a56/Dg7pPbo67uLQulRfpZXjA+SispnPXOjMk5GaNm+zmPTFQqjHjt4H/2VukqS+Prc8j4UnyX4DAhkIxH5UhoUHih4VL+pzXWrp/BhxfrsFlNAZ1oieU9W/iNv52p4sHZRD5jsB1I8eB3dZ4C8lQ3QbtbuQSIkwge6yjwfzqhq34iPLq/FKN6sG66xKWfz7/8h6We7EuLvMR6zLQGZX+Kz9dSlIELpKYBYF3ZSlRThSzA5i6dMHXtPgj3je3NZXTgYVIn4px61EPmmyjhNtAwdCiCcFDgLgzmIXjIQA/NAg8fyv445dVWMT40J6rxYRzfgnBSNGpPvZF+B4I5XBm10hu1aqnaQzd76/vskgcuzFRrZqdU6WZTs9xtR9GIbv1t3ytLXcysBsXSwkIwoHqG8VSsUj0QwSZv2Ap2Uiuc5AGO0J3BJQv0h/7fhBj/NlEsdNazv3KocA7dcznNJHxsaDNvT3os2iUfzBXbNzMoFgIGWlaHnBsKQm4EfTN3StHOzMylh9p4USKD5zhOgYQaZTjFGPjS66hCoMPevl4/Z7BGw1i5E3AjVJo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
